FROM java:8

LABEL "maintainer"="Marcel Bernet <marcel.bernet@ch-open.ch"
LABEL description="IoT Alert Service"

COPY target/alert-service-0.1-jar-with-dependencies.jar /opt/alert-service.jar

CMD java -jar /opt/alert-service.jar