apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: iot-kafka-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-kafka-pipe
  template:
    metadata:
      labels:
        app: iot-kafka-pipe
        tier: backend
        group: java
    spec:
      containers:        
      - name: iot-kafka-pipe
        image: misegr/iot-kafka-pipe
        imagePullPolicy: IfNotPresent        
