apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-kafka-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-kafka-pipe
  template:
    metadata:
      labels:
        app: iot-kafka-pipe
        tier: backend
        group: java
    spec:
      containers:        
      - name: iot-kafka-pipe
        image: registry.gitlab.com/mc-b/iot-kafka/iot-kafka-pipe
        imagePullPolicy: IfNotPresent        
