apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-kafka-consumer
  template:
    metadata:
      labels:
        app: iot-kafka-consumer
        tier: backend
        group: java
    spec:
      containers:        
      - name: iot-kafka-consumer
        image: misegr/iot-kafka-consumer
        imagePullPolicy: IfNotPresent        
